GET  http://localhost:3040/api/user/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0LCJlbWFpbCI6InNhbXVlbGh1cnRhZG9AZ21haWwuY29tIiwibmFtZSI6IlNhbXVlbCBIdXJ0YWRvIiwicGFzc3dvcmQiOiIiLCJyb2wiOiJBZG1pbiJ9LCJpYXQiOjE2NTA1NDYxNTh9.J1Lpq7vCTZdjSH5RdMREd-i4UWHPbRRWHxKeWv7zuZ8